name: farm_mobile
description: Farm-to-market mobile app (farmer & shop roles)
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.4.2
  equatable: ^2.0.5
  url_launcher: ^6.3.0
  hooks_riverpod: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^13.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
